/**
 * AI and Voice provider configuration.
 * Uses centralized config for provider selection and API keys.
 */

import { type AIProvider, config } from "./config.ts";
import { XaiVoice } from "./xai-voice.ts";
import { OpenAIVoice } from "@mastra/voice-openai";

// Model mappings per provider
const AI_PROVIDER_MODELS: Record<
  AIProvider,
  { summary: string; main: string }
> = {
  xai: { summary: "grok-4.3", main: "grok-4.3" },
  openai: { summary: "gpt-5-mini", main: "gpt-5.2" },
  anthropic: { summary: "claude-haiku-4-5", main: "claude-sonnet-4-5" },
  google: { summary: "gemini-3-pro-preview", main: "gemini-3-flash-preview" },
};

// OpenAI voice settings
const OPENAI_VOICE_CONFIG = {
  model: "gpt-4o-mini-tts",
  speaker: "nova",
  instructions:
    "You are podcaster reading today's latest news articles to your audience, " +
    "with excitement and intrigue in your voice to engage readers and entertain them. " +
    "Ensure you add pauses in between what you're saying to emphasize.",
};

/**
 * Get model config for Mastra agents
 */
export function getAgentModelConfig(type: "summary" | "main"): {
  id: `${string}/${string}`;
  apiKey: string;
} {
  const provider = config.aiProvider;
  const apiKey = config.apiKeys[provider];

  if (!apiKey) {
    throw new Error(`API key required for ${provider} provider`);
  }

  return {
    id: `${provider}/${AI_PROVIDER_MODELS[provider][type]}`,
    apiKey,
  };
}

/**
 * Structural interface for the voice provider methods this project uses.
 *
 * We avoid typing against `MastraVoice` directly because `@mastra/voice-openai`
 * bundles its own copy of `@mastra/core` (private fields make the types
 * structurally incompatible across packages). Both OpenAIVoice and our XaiVoice
 * satisfy this minimal interface.
 */
export interface VoiceLike {
  speak(
    input: string | NodeJS.ReadableStream,
    options?: Record<string, unknown>,
  ): Promise<NodeJS.ReadableStream | void>;
}

/**
 * A configured voice provider plus the provider-specific options to pass
 * to each `speak()` call. This abstracts over OpenAI vs xAI TTS so the
 * workflow doesn't need to know which provider is in use.
 */
export interface VoiceProviderHandle {
  voice: VoiceLike;
  speakOptions: Record<string, unknown>;
}

/**
 * Create the configured voice provider for TTS.
 * Supports OpenAI (default) and xAI (Grok) via VOICE_PROVIDER.
 */
export function createVoiceProvider(): VoiceProviderHandle {
  switch (config.voiceProvider) {
    case "xai": {
      const apiKey = config.apiKeys.xai;
      if (!apiKey) {
        throw new Error("XAI_API_KEY is required for the xAI voice provider");
      }
      const voice = new XaiVoice({
        apiKey,
        speaker: config.xaiVoiceId,
        language: config.xaiVoiceLanguage,
      });
      // xAI TTS has no "instructions"/persona prompt; speed is the main knob.
      return { voice, speakOptions: {} };
    }
    case "openai":
    default: {
      const apiKey = config.apiKeys.openai;
      if (!apiKey) {
        throw new Error(
          "OPENAI_API_KEY is required for the OpenAI voice provider",
        );
      }
      // Note: Mastra voice-openai types only list tts-1/tts-1-hd, but
      // gpt-4o-mini-tts works at runtime via OpenAI's API
      const voice = new OpenAIVoice({
        speechModel: {
          // deno-lint-ignore no-explicit-any
          name: OPENAI_VOICE_CONFIG.model as any,
          apiKey,
        },
        speaker: OPENAI_VOICE_CONFIG.speaker,
      });
      return {
        voice,
        speakOptions: { instructions: OPENAI_VOICE_CONFIG.instructions },
      };
    }
  }
}

/**
 * xAI TTS understands inline "speech tags" that add natural, human-like
 * delivery (pauses, laughter, whispers, pacing). These are sent verbatim in
 * the text and interpreted by the API. Other providers (e.g. OpenAI) would
 * read such tags aloud as literal words, so this returns guidance only when
 * the xAI voice provider is selected.
 *
 * Returns instructions the script-writing agents can follow, or an empty
 * string when tags are unsupported (so prompts stay unchanged).
 */
export function getSpeechTagGuidance(): string {
  if (config.voiceProvider !== "xai") return "";

  return `
Delivery tags for natural, human-like speech (IMPORTANT - the audio sounds flat without them):
The audio is generated by xAI (Grok) TTS, which understands inline delivery tags embedded right in the text. These are how you make the podcast sound like a real, expressive human host rather than a flat read. Use them wherever a real person speaking this aloud would naturally pause, emphasize, or react.

Your toolkit - the ONLY tags you may use. No other tags exist; inventing or using any tag not listed here will be read aloud as literal text and ruin the audio:
- [pause] for a short beat, [long-pause] for a dramatic pause. These are your most useful tools.
- <whisper>...</whisper> to drop to a conspiratorial whisper for "here's the secret" emphasis (wrap a complete phrase, never a single word).
- <soft>...</soft> for a gentle, warm delivery.
- <slow>...</slow> to draw out and emphasize an important takeaway or punchline.

Where to use them (place tags inline within paragraphs, never alone on their own line):
- A [pause] at every transition between stories, right after the connecting phrase ("Switching gears... [pause]")
- A [pause] or [long-pause] right before a surprising reveal, key number, or punchline so it lands ("and the price tag? [long-pause] Twelve thousand dollars.")
- <slow> around the single most important takeaway of a story
- <whisper> for a "between you and me" aside, used rarely (once or twice)
- Combine with punctuation for the most natural result: "Really? [pause] I did not see that coming."

Aim for natural variety - several [pause]s across the script and occasional emphasis. Do not stack tags or put them on every sentence, but do use them - a flat read with zero tags sounds robotic. Remember: if a tag is not in your toolkit above, do not use it - only the five tags listed exist.
`;
}
